-- MySQL Script generated by MySQL Workbench
-- Wed Dec 18 00:20:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema relocants_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema relocants_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `relocants_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `relocants_db` ;

-- -----------------------------------------------------
-- Table `relocants_db`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relocants_db`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `relocants_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relocants_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `avatar_url` VARCHAR(255) NULL DEFAULT NULL,
  `registration_date` DATETIME NOT NULL,
  `refresh_token` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `refresh_token_UNIQUE` (`refresh_token` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `relocants_db`.`documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relocants_db`.`documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `title_ru` VARCHAR(255) NOT NULL,
  `title_pl` VARCHAR(255) NOT NULL,
  `description_ru` VARCHAR(511) NULL DEFAULT NULL,
  `description_pl` VARCHAR(511) NULL DEFAULT NULL,
  `default_photo_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `documents_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `relocants_db`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `relocants_db`.`document_photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relocants_db`.`document_photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `document_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `file_url` VARCHAR(255) NOT NULL,
  `upload_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `document_id` (`document_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `document_photos_ibfk_1`
    FOREIGN KEY (`document_id`)
    REFERENCES `relocants_db`.`documents` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `document_photos_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `relocants_db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `relocants_db`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relocants_db`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `creator_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(511) NULL DEFAULT NULL,
  `start_date_time` DATETIME NOT NULL,
  `total_seats` INT NOT NULL,
  `registered_seats` INT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `creator_id` (`creator_id` ASC) VISIBLE,
  CONSTRAINT `events_ibfk_1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `relocants_db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `relocants_db`.`event_photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relocants_db`.`event_photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `file_url` VARCHAR(255) NOT NULL,
  `upload_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `event_id` (`event_id` ASC) VISIBLE,
  CONSTRAINT `event_photos_ibfk_1`
    FOREIGN KEY (`event_id`)
    REFERENCES `relocants_db`.`events` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `relocants_db`.`event_registrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relocants_db`.`event_registrations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `event_id` (`event_id` ASC) VISIBLE,
  CONSTRAINT `event_registrations_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `relocants_db`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `event_registrations_ibfk_2`
    FOREIGN KEY (`event_id`)
    REFERENCES `relocants_db`.`events` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `relocants_db`.`instructions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relocants_db`.`instructions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title_ru` VARCHAR(255) NOT NULL,
  `title_pl` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `relocants_db`.`notification_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relocants_db`.`notification_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `message` VARCHAR(511) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `relocants_db`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relocants_db`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `notification_type_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `related_user_id` INT NULL DEFAULT NULL,
  `notification_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `notification_type_id` (`notification_type_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `related_user_id` (`related_user_id` ASC) VISIBLE,
  CONSTRAINT `notifications_ibfk_1`
    FOREIGN KEY (`notification_type_id`)
    REFERENCES `relocants_db`.`notification_types` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `notifications_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `relocants_db`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `notifications_ibfk_3`
    FOREIGN KEY (`related_user_id`)
    REFERENCES `relocants_db`.`users` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `relocants_db`.`steps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relocants_db`.`steps` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `instruction_id` INT NOT NULL,
  `title_ru` VARCHAR(255) NOT NULL,
  `title_pl` VARCHAR(255) NOT NULL,
  `description_ru` VARCHAR(511) NULL DEFAULT NULL,
  `description_pl` VARCHAR(511) NULL DEFAULT NULL,
  `document_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `instruction_id` (`instruction_id` ASC) VISIBLE,
  INDEX `document_id` (`document_id` ASC) VISIBLE,
  CONSTRAINT `steps_ibfk_1`
    FOREIGN KEY (`instruction_id`)
    REFERENCES `relocants_db`.`instructions` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `steps_ibfk_2`
    FOREIGN KEY (`document_id`)
    REFERENCES `relocants_db`.`documents` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `relocants_db`.`streets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relocants_db`.`streets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city_id` INT NOT NULL,
  `street_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `city_id` (`city_id` ASC) VISIBLE,
  CONSTRAINT `streets_ibfk_1`
    FOREIGN KEY (`city_id`)
    REFERENCES `relocants_db`.`cities` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `relocants_db`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relocants_db`.`subscriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subscriber_id` INT NOT NULL,
  `subscribed_to_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `subscriber_id` (`subscriber_id` ASC) VISIBLE,
  INDEX `subscribed_to_id` (`subscribed_to_id` ASC) VISIBLE,
  CONSTRAINT `subscriptions_ibfk_1`
    FOREIGN KEY (`subscriber_id`)
    REFERENCES `relocants_db`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `subscriptions_ibfk_2`
    FOREIGN KEY (`subscribed_to_id`)
    REFERENCES `relocants_db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
